name: CI
on:
  push:
    branches:
      - "main"
  pull_request:

# This allows a subsequently queued workflow run to interrupt previous runs
concurrency:
  group: "${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}"
  cancel-in-progress: true

jobs:
  build-test:
    name: "build+test"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.2.2

      - name: Set up Go
        uses: actions/setup-go@v5.5.0
        with:
          go-version: stable

      - name: Build
        run: go build -v ./...

      - name: Test
        run: go test -v -shuffle on ./...
